name = "backend"
compatibility_date = "2024-08-26"

#[vars]
#DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTNlMWE2ZGQtZWVlOC00M2I1LTliYzUtNjk2OWY1MDVkZGRmIiwidGVuYW50X2lkIjoiNjhkN2FhZjYzMzg3MzI4MWRmOTc2NGM4ZDdhOWI4YmRmZDU1MzFmYzcyMjZlNmYzYjI0YjFhNDRkZDVmYjEzNSIsImludGVybmFsX3NlY3JldCI6IjNhOGQzNGQ2LTE3ZmEtNDRjMS1iYjMzLThiNDgwNGQ3NTVhMSJ9.VESa5Q8JOJHG3Y_Ld-nYfkEsel1lGYRMPT2pAe2PbaA"

[env.production]
vars = { DATABASE_URL = "$DATABASE_POOL_URL" }